name: Deploy React App to EC2

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t react-app:latest ./react

      - name: Stop Old Container (if running)
        run: |
          docker stop react-app || true
          docker rm react-app || true

      - name: Run Docker Container
        run: |
          docker run -d --name react-app -p 80:80 react-app:latest
